# Rose Dennis, rad7wgg
# Midterm Assignment 

#Cleaning and Smoothing of Data
####################################################################

### Deleting Columns not used in Analysis 
survey <- survey[-c(1,9,10,17)]
### Checking and Removing N/A Values in survey Dataframe
any(is.na(survey))
survey <- survey[-35, ]
survey <- survey[-34, ]
survey <- survey[-33, ]
survey <- survey[-32, ]

### Binning and Discreteizing Data to Add to Dataframe
### Raw data is continuous(percentages) and requires discretizing. Put into 5 bins that range from 0.0-0.2(Very Low), 0.2-0.4(Low), 0.4-0.6(Moderate), 0.6-0.8(High), 0.8-1.0(Very High) 

# Binning Mood Value
Mood <- survey$Mood
cut(Mood, c(-Inf, 0.2, 0.4, 0.6, 0.8, Inf), labels=  c("Very Low","Low","Moderate","High","Very High"))
survey$BinMood <- cut(Mood, c(-Inf, 0.2, 0.4, 0.6, 0.8, Inf), labels=  c("Very Low","Low","Moderate","High","Very High"))
# Binning Stress Value
Stress <- survey$Stress
cut(Stress, c(-Inf, 0.2, 0.4, 0.6, 0.8, Inf), labels=  c("Very Low","Low","Moderate","High","Very High"))
survey$BinStress <- cut(Stress, c(-Inf, 0.2, 0.4, 0.6, 0.8, Inf), labels=  c("Very Low","Low","Moderate","High","Very High"))
# Binning Productivity Value
Productivity <- survey$Productivity
cut(Productivity, c(-Inf, 0.2, 0.4, 0.6, 0.8, Inf), labels=  c("Very Low","Low","Moderate","High","Very High"))
survey$BinProductivity <- cut(Productivity, c(-Inf, 0.2, 0.4, 0.6, 0.8, Inf), labels=  c("Very Low","Low","Moderate","High","Very High"))
# Binning Energy Value
Energy <- survey$Energy
cut(Energy, c(-Inf, 0.2, 0.4, 0.6, 0.8, Inf), labels=  c("Very Low","Low","Moderate","High","Very High"))
survey$BinEnergy <- cut(Energy, c(-Inf, 0.2, 0.4, 0.6, 0.8, Inf), labels=  c("Very Low","Low","Moderate","High","Very High"))

### Binning Quality Index Value (Aggregate of Factors) Mood + Productivity + Energy - Stress (Stress is seen as a negative factor to overall quality):
Quality_Index <- survey$Quality_Index
cut(Quality_Index, c(-Inf, 0.4, 0.8, 1.2, 1.6, Inf), labels=  c("Very Low","Low","Moderate","High","Very High"))
survey$BinQuality_Index <- cut(Quality_Index, c(-Inf, 0.4, 0.8, 1.2, 1.6, Inf), labels=  c("Very Low","Low","Moderate","High","Very High"))

### Replacing Excercise Column Numeric Values to Night and Morning:
class(survey$Exercise_Time)
survey$Exercise_Time[survey$Exercise_Time == "3"] <- "Night"
survey$Exercise_Time[survey$Exercise_Time == "4"] <- "Night"
survey$Exercise_Time[survey$Exercise_Time == "1"] <- "Morning"

### Replacing Number_Meals Column's Numeric Values to 2 Meals or 3 Meals:
class(survey$Number_Meals)
survey$Number_Meals[survey$Number_Meals == "2"] <- "2 Meals"
survey$Number_Meals[survey$Number_Meals == "3"] <- "3 Meals"

#Plotting of Data
####################################################################
library(ggplot2)

### Plotting Days vs. Time of Exercise and Filling Plots with Mood:
ggplot(survey, aes(x = Exercise_Time, fill = BinMood)) +
theme_bw() +
geom_bar() +
labs( y = "Day", x = "Time of Excercise") +
scale_fill_discrete(name = 'Mood', h = c(360,180) + 25, c = 100, l=65, h.start = 0,  direction = 1, na.value = "grey50") 

### Plotting Days vs. Time of Exercise and Filling Plots with Stress:
ggplot(survey, aes(x = Exercise_Time, fill = BinStress)) +
theme_bw() +
geom_bar() +
labs( y = "Day", x = "Time of Excercise") +
scale_fill_discrete(name = 'Stress', h = c(360,180) + 25, c = 100, l=65, h.start = 0,  direction = 1, na.value = "grey50") 

### Plotting Days vs. Time of Exercise and Filling Plots with Energy:
ggplot(survey, aes(x = Exercise_Time, fill = BinEnergy)) +
theme_bw() +
geom_bar() +
labs( y = "Day", x = "Time of Excercise") +
scale_fill_discrete(name = 'Energy', h = c(360,180) + 25, c = 100, l=65, h.start = 0,  direction = 1, na.value = "grey50") 

### Plotting Days vs. Time of Exercise and Filling Plots with Productivity:
ggplot(survey, aes(x = Exercise_Time, fill = BinProductivity)) +
theme_bw() +
geom_bar() +
labs( y = "Day", x = "Time of Excercise") +
scale_fill_discrete(name = 'Productivity', h = c(360,180) + 25, c = 100, l=65, h.start = 0,  direction = 1, na.value = "grey50") 

### Creating a Bar Graph of Quality Index (Aggregate of Factors):
ggplot(survey, aes(x = Exercise_Time, fill = BinQuality_Index)) +
theme_bw() +
geom_bar() +
labs( y = "Day", x = "Time of Excercise") +
scale_fill_discrete(name = 'Quality Index', h = c(360,180) + 25, c = 100, l=65, h.start = 0,  direction = 1, na.value = "grey50")


### Creating a Density Graph of Quality Index (Aggregate of Factors):
ggplot(survey, aes(x = Quality_Index, fill = Exercise_Time)) +
theme_bw() +
geom_density (alpha = 0.5) +
labs( y = "Density", x = "Quality Index") +
scale_fill_discrete(name = 'Time Exercised')

### Graphing Meals Eaten along with the Composite Graph of all Factors:
ggplot(survey, aes(x = Exercise_Time, fill = BinQuality_Index)) +
theme_bw() +
facet_wrap(~ Number_Meals) +
geom_bar() +
labs( y = "Day", x = "Time of Excercise") +
scale_fill_discrete(name = 'Quality Index', h = c(360,180) + 25, c = 100, l=65, h.start = 0,  direction = 1, na.value = "grey50") 

#Saving survey Final Dataframe as a csv file
####################################################################
survey <- survey[-c(1,2,3,4,5,6,13)]
write.csv(survey, "PIEL_Survey_RFinalDF_Cleaned")

# Creating a graph before binning to show the downfalls of it:
ggplot(survey, aes(x=Energy)) + geom_bar()



